server:
    port: 8081

web3j:
    client-address: https://mainnet.infura.io/v3/cf58adcd29694b688d88c27136291ace

spring:
  application:
    name: ethereum-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ethereum?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
