### 获取最新的区块号
GET http://localhost:8081/chainData/blockNumber
Accept: application/json

### 获取所有账户
GET http://localhost:8081/chainData/accounts
Accept: application/json

### 获取Gas价格
GET http://localhost:8081/chainData/gasPrice
Accept: application/json

### 获取链Id
GET http://localhost:8081/chainData/chainId
Accept: application/json

### 获取CoinBase
GET http://localhost:8081/chainData/coinbase
Accept: application/json

### 根据区块号获取区块信息
GET http://localhost:8081/chainData/getBlockInfo?blockNumber=15714799
Accept: application/json

### 根据区块号获取所有交易
GET http://localhost:8081/chainData/getTransactionByBlockNumber?blockNumber=15714799
Accept: application/json

### 根据交易哈希值获取交易信息
GET http://localhost:8081/chainData/getTransactionInfoByHash?txHash=0xbf69f45ed55a9405dd04021fed705b2dbb44066f4d3c91178ac8226edb04a1ed
Accept: application/json

### 根据交易哈希值获取交易回执
#GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0x690f828773d2ddf2a0028bbd60084a5db7275fff1353fae003a016a8ac0ed0eb
#GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0xe3577e9ca406cd0f14646539d14b22885e7325003259f6723ca0aee4fd1d6048
GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0x256e7cae6a59235ce2938c54073e16a98dd553ab5263552700255b20a8148923
Accept: application/json














