### 获取最新的区块号
GET http://localhost:8081/chainData/blockNumber
Accept: application/json

### 获取所有账户
GET http://localhost:8081/chainData/accounts
Accept: application/json

### 获取Gas价格
GET http://localhost:8081/chainData/gasPrice
Accept: application/json

### 获取链Id
GET http://localhost:8081/chainData/chainId
Accept: application/json

### 获取CoinBase
GET http://localhost:8081/chainData/coinbase
Accept: application/json

### 根据区块号获取区块信息
GET http://localhost:8081/chainData/getBlockInfo?blockNumber=15714799
Accept: application/json

### 根据区块号获取所有交易
GET http://localhost:8081/chainData/getTransactionByBlockNumber?blockNumber=15714799
Accept: application/json

### 根据交易哈希值获取交易信息
# GET http://localhost:8081/chainData/getTransactionInfoByHash?txHash=0xebc9683ff37b4bb5fec849cc95681dea18d6fcfce6e9c88554d06a25e0ecfdaa
# GET http://localhost:8081/chainData/getTransactionInfoByHash?txHash=0x9876ea63adf0a0c4880c09231dd030a0a80f7aa3004f0d325d1c2da3d1bac4d1
GET http://localhost:8081/chainData/getTransactionInfoByHash?txHash=0xe3e9323a7d9287cc1e934790470a9f83f9866acdca0d08cf8b857b9a90057cf0
Accept: application/json

### 根据交易哈希值获取交易回执
# GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0xebc9683ff37b4bb5fec849cc95681dea18d6fcfce6e9c88554d06a25e0ecfdaa
# GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0x9876ea63adf0a0c4880c09231dd030a0a80f7aa3004f0d325d1c2da3d1bac4d1
GET http://localhost:8081/chainData/getTransactionReceiptByHash?txHash=0xe3e9323a7d9287cc1e934790470a9f83f9866acdca0d08cf8b857b9a90057cf0
Accept: application/json














