### 获取最新的区块号
GET http://localhost:8081/chainInfo/blockNumber
Accept: application/json

### 获取所有账户
GET http://localhost:8081/chainInfo/accounts
Accept: application/json

### 获取Gas价格
GET http://localhost:8081/chainInfo/gasPrice
Accept: application/json

### 获取链Id
GET http://localhost:8081/chainInfo/chainId
Accept: application/json

### 获取CoinBase
GET http://localhost:8081/chainInfo/coinbase
Accept: application/json

### 根据区块号获取区块信息
GET http://localhost:8081/chainInfo/getBlockInfo?blockNumber=15709737
Accept: application/json

### 根据区块号获取所有交易
GET http://localhost:8081/chainInfo/getTransactionByBlockNumber?blockNumber=15709737
Accept: application/json

### 根据交易哈希值获取交易信息
GET http://localhost:8081/chainInfo/getTransactionInfoByHash?txHash=0xa6840780a37c577aae557486dd71030c392cb7ca62f0ca13143a4c676463ee7c
Accept: application/json
















